// Generated by scripts/build.mjs from src/; edit the sources, not this file.
"use strict";
(() => {
  // src/ui/settings.ts
  var host = window.CanvasTTYPlugin;
  var SERVICE = "assistant";
  var STRINGS = {
    en: {
      title: "Assistant",
      lead: "Reviews agents' commands and triages tasks with a small decision model: Jev (TypeSafe, OpenRouter, Vercel), Laya, an Eikos server, or a model on your Ollama. Off by default; while off nothing runs.",
      enabled: "Assistant on",
      modes: "Modes",
      review: "Command review",
      triage: "Task triage (launch and orchestrator)",
      off: "Off",
      shadow: "Learning",
      suggest: "Suggest",
      auto: "Auto",
      modeHelp: "Learning records answers only. Suggest shows them on the card and enforces nothing. Auto may ask you or decline; it allows only what has qualified on your own answers, and only if CanvasTTY lets this plugin allow.",
      strictness: "Review strictness",
      byTask: "By the task (triage)",
      always: "Always strict",
      yolo: "YOLO only in an isolated environment (worktree, container, server)",
      data: "Data",
      dataMode: "Data check",
      strict: "Strict",
      warn: "Warn only",
      dataOff: "Off",
      grant: "What may leave this computer",
      grantOff: "Only code facts (no text)",
      grantD1: "Texts up to D1",
      grantD2: "Texts up to D2",
      defaultClass: "Class of card text",
      engine: "Where it runs",
      engineAuto: "Jev first, then this computer",
      engineJev: "Jev only",
      engineLocal: "This computer only",
      backends: "Decision models",
      none: "None yet.",
      add: "Add",
      model: "Model",
      url: "Address",
      local: "This server runs on this computer and sends nothing anywhere",
      check: "Check",
      checking: "Checking\u2026",
      remove: "Remove",
      enabledBackend: "On",
      key: "Key",
      keySet: "key saved",
      keyNone: "no key",
      saveKey: "Save key",
      removeKey: "Remove key",
      trust: "I trust it with",
      where: { local: "this computer", remote: "leaves this computer" },
      checkOk: (r) => `OK: ${r.modelLabel ?? "the model"} answered${r.latencyMs !== null ? ` in ${r.latencyMs} ms` : ""} (${r.requests} requests).`,
      checkFail: (r) => `Not usable: ${r.checks.filter((c) => c.status === "fail").map((c) => c.detail).join(" ") || r.failure || "the check failed"}`,
      smart: "Second reviewer (larger local Ollama model)",
      smartNone: "None",
      smartModel: "Ollama model",
      smartAsk: "While learning, also ask the second reviewer",
      recent: "Recent reviews",
      noRecent: "Nothing reviewed yet.",
      right: "Right",
      wrong: "Wrong",
      saved: "Saved.",
      notSaved: "Not saved: "
    },
    ru: {
      title: "\u041F\u043E\u043C\u043E\u0449\u043D\u0438\u043A",
      lead: "\u041F\u0440\u043E\u0432\u0435\u0440\u044F\u0435\u0442 \u043A\u043E\u043C\u0430\u043D\u0434\u044B \u0430\u0433\u0435\u043D\u0442\u043E\u0432 \u0438 \u0440\u0430\u0437\u0431\u0438\u0440\u0430\u0435\u0442 \u0437\u0430\u0434\u0430\u0447\u0438 \u043C\u0430\u043B\u0435\u043D\u044C\u043A\u043E\u0439 \u043C\u043E\u0434\u0435\u043B\u044C\u044E \u0440\u0435\u0448\u0435\u043D\u0438\u0439: Jev (TypeSafe, OpenRouter, Vercel), Laya, \u0441\u0435\u0440\u0432\u0435\u0440 Eikos \u0438\u043B\u0438 \u043C\u043E\u0434\u0435\u043B\u044C \u0432 \u0432\u0430\u0448\u0435\u0439 Ollama. \u041F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E \u0432\u044B\u043A\u043B\u044E\u0447\u0435\u043D; \u0432\u044B\u043A\u043B\u044E\u0447\u0435\u043D\u043D\u044B\u0439 \u043D\u0438\u0447\u0435\u0433\u043E \u043D\u0435 \u0437\u0430\u043F\u0443\u0441\u043A\u0430\u0435\u0442.",
      enabled: "\u041F\u043E\u043C\u043E\u0449\u043D\u0438\u043A \u0432\u043A\u043B\u044E\u0447\u0451\u043D",
      modes: "\u0420\u0435\u0436\u0438\u043C\u044B",
      review: "\u041F\u0440\u043E\u0432\u0435\u0440\u043A\u0430 \u043A\u043E\u043C\u0430\u043D\u0434",
      triage: "\u0420\u0430\u0437\u0431\u043E\u0440 \u0437\u0430\u0434\u0430\u0447\u0438 (\u0437\u0430\u043F\u0443\u0441\u043A \u0438 \u043E\u0440\u043A\u0435\u0441\u0442\u0440\u0430\u0442\u043E\u0440)",
      off: "\u0412\u044B\u043A\u043B",
      shadow: "\u041E\u0431\u0443\u0447\u0435\u043D\u0438\u0435",
      suggest: "\u041F\u043E\u0434\u0441\u043A\u0430\u0437\u043A\u0438",
      auto: "\u0410\u0432\u0442\u043E",
      modeHelp: "\u041E\u0431\u0443\u0447\u0435\u043D\u0438\u0435 \u0442\u043E\u043B\u044C\u043A\u043E \u0437\u0430\u043F\u0438\u0441\u044B\u0432\u0430\u0435\u0442 \u043E\u0442\u0432\u0435\u0442\u044B. \u041F\u043E\u0434\u0441\u043A\u0430\u0437\u043A\u0438 \u043F\u043E\u043A\u0430\u0437\u044B\u0432\u0430\u044E\u0442 \u0438\u0445 \u043D\u0430 \u043E\u043A\u043D\u0435 \u0438 \u043D\u0438\u0447\u0435\u0433\u043E \u043D\u0435 \u0440\u0435\u0448\u0430\u044E\u0442. \u0410\u0432\u0442\u043E \u043C\u043E\u0436\u0435\u0442 \u0441\u043F\u0440\u043E\u0441\u0438\u0442\u044C \u0432\u0430\u0441 \u0438\u043B\u0438 \u043E\u0442\u043A\u0430\u0437\u0430\u0442\u044C; \u0440\u0430\u0437\u0440\u0435\u0448\u0430\u0435\u0442 \u0442\u043E\u043B\u044C\u043A\u043E \u0442\u043E, \u0447\u0442\u043E \u043F\u0440\u043E\u0448\u043B\u043E \u043F\u0440\u043E\u0432\u0435\u0440\u043A\u0443 \u043D\u0430 \u0432\u0430\u0448\u0438\u0445 \u043E\u0442\u0432\u0435\u0442\u0430\u0445, \u0438 \u0442\u043E\u043B\u044C\u043A\u043E \u0435\u0441\u043B\u0438 CanvasTTY \u0440\u0430\u0437\u0440\u0435\u0448\u0438\u043B \u044D\u0442\u043E\u043C\u0443 \u043F\u043B\u0430\u0433\u0438\u043D\u0443 \u0440\u0430\u0437\u0440\u0435\u0448\u0430\u0442\u044C.",
      strictness: "\u0421\u0442\u0440\u043E\u0433\u043E\u0441\u0442\u044C \u043F\u0440\u043E\u0432\u0435\u0440\u043A\u0438",
      byTask: "\u041F\u043E \u0437\u0430\u0434\u0430\u0447\u0435 (\u0440\u0430\u0437\u0431\u043E\u0440)",
      always: "\u0412\u0441\u0435\u0433\u0434\u0430 \u0441\u0442\u0440\u043E\u0433\u043E",
      yolo: "YOLO \u0442\u043E\u043B\u044C\u043A\u043E \u0432 \u0438\u0437\u043E\u043B\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u043E\u0439 \u0441\u0440\u0435\u0434\u0435 (worktree, \u043A\u043E\u043D\u0442\u0435\u0439\u043D\u0435\u0440, \u0441\u0435\u0440\u0432\u0435\u0440)",
      data: "\u0414\u0430\u043D\u043D\u044B\u0435",
      dataMode: "\u041F\u0440\u043E\u0432\u0435\u0440\u043A\u0430 \u0434\u0430\u043D\u043D\u044B\u0445",
      strict: "\u0421\u0442\u0440\u043E\u0433\u043E",
      warn: "\u0422\u043E\u043B\u044C\u043A\u043E \u043F\u0440\u0435\u0434\u0443\u043F\u0440\u0435\u0436\u0434\u0430\u0442\u044C",
      dataOff: "\u0412\u044B\u043A\u043B",
      grant: "\u0427\u0442\u043E \u043C\u043E\u0436\u0435\u0442 \u0443\u0439\u0442\u0438 \u0441 \u044D\u0442\u043E\u0433\u043E \u043A\u043E\u043C\u043F\u044C\u044E\u0442\u0435\u0440\u0430",
      grantOff: "\u0422\u043E\u043B\u044C\u043A\u043E \u0441\u043B\u0443\u0436\u0435\u0431\u043D\u044B\u0435 \u043F\u0440\u0438\u0437\u043D\u0430\u043A\u0438 (\u0431\u0435\u0437 \u0442\u0435\u043A\u0441\u0442\u0430)",
      grantD1: "\u0422\u0435\u043A\u0441\u0442\u044B \u0434\u043E D1",
      grantD2: "\u0422\u0435\u043A\u0441\u0442\u044B \u0434\u043E D2",
      defaultClass: "\u041A\u043B\u0430\u0441\u0441 \u0442\u0435\u043A\u0441\u0442\u0430 \u043E\u043A\u043D\u0430",
      engine: "\u0413\u0434\u0435 \u0440\u0430\u0431\u043E\u0442\u0430\u0435\u0442",
      engineAuto: "\u0421\u043D\u0430\u0447\u0430\u043B\u0430 Jev, \u043F\u043E\u0442\u043E\u043C \u044D\u0442\u043E\u0442 \u043A\u043E\u043C\u043F\u044C\u044E\u0442\u0435\u0440",
      engineJev: "\u0422\u043E\u043B\u044C\u043A\u043E Jev",
      engineLocal: "\u0422\u043E\u043B\u044C\u043A\u043E \u044D\u0442\u043E\u0442 \u043A\u043E\u043C\u043F\u044C\u044E\u0442\u0435\u0440",
      backends: "\u041C\u043E\u0434\u0435\u043B\u0438 \u0440\u0435\u0448\u0435\u043D\u0438\u0439",
      none: "\u041F\u043E\u043A\u0430 \u043D\u0435\u0442.",
      add: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C",
      model: "\u041C\u043E\u0434\u0435\u043B\u044C",
      url: "\u0410\u0434\u0440\u0435\u0441",
      local: "\u0421\u0435\u0440\u0432\u0435\u0440 \u0440\u0430\u0431\u043E\u0442\u0430\u0435\u0442 \u043D\u0430 \u044D\u0442\u043E\u043C \u043A\u043E\u043C\u043F\u044C\u044E\u0442\u0435\u0440\u0435 \u0438 \u043D\u0438\u043A\u0443\u0434\u0430 \u043D\u0435 \u043E\u0442\u043F\u0440\u0430\u0432\u043B\u044F\u0435\u0442 \u0434\u0430\u043D\u043D\u044B\u0435",
      check: "\u041F\u0440\u043E\u0432\u0435\u0440\u0438\u0442\u044C",
      checking: "\u041F\u0440\u043E\u0432\u0435\u0440\u044F\u044E\u2026",
      remove: "\u0423\u0434\u0430\u043B\u0438\u0442\u044C",
      enabledBackend: "\u0412\u043A\u043B",
      key: "\u041A\u043B\u044E\u0447",
      keySet: "\u043A\u043B\u044E\u0447 \u0441\u043E\u0445\u0440\u0430\u043D\u0451\u043D",
      keyNone: "\u043D\u0435\u0442 \u043A\u043B\u044E\u0447\u0430",
      saveKey: "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C \u043A\u043B\u044E\u0447",
      removeKey: "\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u043A\u043B\u044E\u0447",
      trust: "\u0414\u043E\u0432\u0435\u0440\u044F\u044E \u0434\u043E",
      where: { local: "\u044D\u0442\u043E\u0442 \u043A\u043E\u043C\u043F\u044C\u044E\u0442\u0435\u0440", remote: "\u0443\u0445\u043E\u0434\u0438\u0442 \u0441 \u043A\u043E\u043C\u043F\u044C\u044E\u0442\u0435\u0440\u0430" },
      checkOk: (r) => `\u0420\u0430\u0431\u043E\u0442\u0430\u0435\u0442: ${r.modelLabel ?? "\u043C\u043E\u0434\u0435\u043B\u044C"} \u043E\u0442\u0432\u0435\u0442\u0438\u043B\u0430${r.latencyMs !== null ? ` \u0437\u0430 ${r.latencyMs} \u043C\u0441` : ""} (\u0437\u0430\u043F\u0440\u043E\u0441\u043E\u0432: ${r.requests}).`,
      checkFail: (r) => `\u041D\u0435 \u043F\u043E\u0434\u0445\u043E\u0434\u0438\u0442: ${r.checks.filter((c) => c.status === "fail").map((c) => c.detail).join(" ") || r.failure || "\u043F\u0440\u043E\u0432\u0435\u0440\u043A\u0430 \u043D\u0435 \u043F\u0440\u043E\u0448\u043B\u0430"}`,
      smart: "\u0412\u0442\u043E\u0440\u043E\u0439 \u043F\u0440\u043E\u0432\u0435\u0440\u044F\u044E\u0449\u0438\u0439 (\u0431\u043E\u043B\u044C\u0448\u0430\u044F \u043B\u043E\u043A\u0430\u043B\u044C\u043D\u0430\u044F \u043C\u043E\u0434\u0435\u043B\u044C Ollama)",
      smartNone: "\u041D\u0435\u0442",
      smartModel: "\u041C\u043E\u0434\u0435\u043B\u044C Ollama",
      smartAsk: "\u0412\u043E \u0432\u0440\u0435\u043C\u044F \u043E\u0431\u0443\u0447\u0435\u043D\u0438\u044F \u0442\u043E\u0436\u0435 \u0441\u043F\u0440\u0430\u0448\u0438\u0432\u0430\u0442\u044C \u0432\u0442\u043E\u0440\u043E\u0433\u043E \u043F\u0440\u043E\u0432\u0435\u0440\u044F\u044E\u0449\u0435\u0433\u043E",
      recent: "\u041F\u043E\u0441\u043B\u0435\u0434\u043D\u0438\u0435 \u043F\u0440\u043E\u0432\u0435\u0440\u043A\u0438",
      noRecent: "\u041F\u043E\u043A\u0430 \u043D\u0438\u0447\u0435\u0433\u043E \u043D\u0435 \u043F\u0440\u043E\u0432\u0435\u0440\u044F\u043B\u043E\u0441\u044C.",
      right: "\u0412\u0435\u0440\u043D\u043E",
      wrong: "\u041D\u0435\u0432\u0435\u0440\u043D\u043E",
      saved: "\u0421\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u043E.",
      notSaved: "\u041D\u0435 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u043E: "
    }
  };
  var t = STRINGS.en;
  var state = null;
  var root = document.querySelector("#app");
  var status = document.querySelector("#status");
  var PRESETS = [
    { id: "emulated", label: "Ollama", keyed: false, url: "http://127.0.0.1:11434", model: "qwen3.5:9b" },
    { id: "typesafe", label: "Jev \xB7 TypeSafe", keyed: true, url: null, model: "jev-1.13.0" },
    { id: "openrouter", label: "Jev \xB7 OpenRouter", keyed: true, url: null, model: "typesafe/jev-1.13" },
    { id: "vercel", label: "Jev \xB7 Vercel", keyed: true, url: null, model: "typesafe-ai/jev" },
    { id: "laya", label: "Laya", keyed: false, url: "http://127.0.0.1:8000", model: "typed-decisions" },
    { id: "eikos", label: "Eikos (serve.py)", keyed: false, url: "http://127.0.0.1:8000", model: "eikos" },
    { id: "custom", label: "System One server", keyed: false, url: "https://", model: "default" }
  ];
  function say(message) {
    status.textContent = message;
  }
  var errorText = (error) => error instanceof Error ? error.message : String(error);
  function el(tag, props = {}, ...children) {
    const node = document.createElement(tag);
    const { dataset, ...rest } = props;
    Object.assign(node, rest);
    if (dataset) Object.assign(node.dataset, dataset);
    node.append(...children);
    return node;
  }
  function select(value, options, onChange, name) {
    const node = el("select", { name });
    for (const [option, label] of options) node.append(el("option", { value: option, textContent: label, selected: option === value }));
    node.addEventListener("change", () => onChange(node.value));
    return node;
  }
  function checkbox(checked, label, onChange, name) {
    const input = el("input", { type: "checkbox", checked, name });
    input.addEventListener("change", () => onChange(input.checked));
    return el("label", { className: "check" }, input, ` ${label}`);
  }
  async function load() {
    state = await host.service.request(SERVICE, "state");
    render();
  }
  async function save(change) {
    if (!state) return;
    const next = structuredClone(state.settings);
    change(next);
    try {
      await host.service.request(SERVICE, "save", { settings: next });
      say(t.saved);
    } catch (error) {
      say(`${t.notSaved}${errorText(error)}`);
    }
    await load();
  }
  function modeSelect(useCase) {
    const modes = [["off", t.off], ["shadow", t.shadow], ["suggest", t.suggest], ["auto", t.auto]];
    return select(state.settings.modes[useCase], modes, (value) => void save((s) => {
      s.modes[useCase] = value;
    }), useCase);
  }
  function row(label, control) {
    return el("div", { className: "row" }, el("span", { className: "label", textContent: label }), control);
  }
  function backendRow(entry) {
    const preset = PRESETS.find((item2) => item2.id === entry.preset);
    const info = state.status.backends.find((item2) => item2.id === entry.id);
    const slot = state.slots[entry.id] ?? null;
    const check = state.checks[entry.id];
    const item = el("li", { className: "backend", dataset: { backend: entry.id } });
    const head = el(
      "div",
      { className: "row" },
      el("strong", { textContent: `${preset?.label ?? entry.preset} \xB7 ${entry.model ?? ""}` }),
      el("span", { className: "muted", textContent: `${entry.url ?? ""} \u2014 ${info ? t.where[info.target] : ""}` })
    );
    const controls = el("div", { className: "row" });
    controls.append(checkbox(entry.enabled, t.enabledBackend, (value) => void save((s) => {
      s.backends.find((b) => b.id === entry.id).enabled = value;
    }), `enabled-${entry.id}`));
    if (info?.target === "remote") {
      controls.append(el("span", { className: "label", textContent: t.trust }), select(entry.trust ?? "D0", [["D0", "D0"], ["D1", "D1"], ["D2", "D2"]], (value) => void save((s) => {
        s.backends.find((b) => b.id === entry.id).trust = value;
      }), `trust-${entry.id}`));
    }
    const checkButton = el("button", { type: "button", textContent: t.check, name: `check-${entry.id}` });
    checkButton.addEventListener("click", () => {
      say(t.checking);
      host.service.request(SERVICE, "check", { backendId: entry.id }).then(() => load(), (error) => say(errorText(error)));
    });
    const removeButton = el("button", { type: "button", textContent: t.remove });
    removeButton.addEventListener("click", () => void save((s) => {
      s.backends = s.backends.filter((b) => b.id !== entry.id);
    }));
    controls.append(checkButton, removeButton);
    item.append(head, controls);
    if (slot) {
      const input = el("input", { type: "password", placeholder: t.key, autocomplete: "off", name: `key-${entry.id}` });
      const saveKey = el("button", { type: "button", textContent: t.saveKey });
      saveKey.addEventListener("click", async () => {
        const value = input.value.trim();
        input.value = "";
        if (!value) return;
        try {
          await host.secrets.set(slot.secret, JSON.stringify({ origin: slot.origin, value }));
          await host.service.request(SERVICE, "keyChanged", { backendId: entry.id });
          say(t.saved);
        } catch (error) {
          say(`${t.notSaved}${errorText(error)}`);
        }
        await load();
      });
      const removeKey = el("button", { type: "button", textContent: t.removeKey });
      removeKey.addEventListener("click", async () => {
        try {
          await host.secrets.delete(slot.secret);
          await host.service.request(SERVICE, "keyChanged", { backendId: entry.id });
        } catch (error) {
          say(errorText(error));
        }
        await load();
      });
      item.append(el("div", { className: "row" }, el("span", { className: "muted", textContent: info?.keyConfigured ? t.keySet : t.keyNone }), input, saveKey, removeKey));
    }
    if (check) {
      const line = "running" in check ? t.checking : "error" in check ? check.error : check.added ? t.checkOk(check) : t.checkFail(check);
      item.append(el("div", { className: "check-result", textContent: line, dataset: { result: entry.id } }));
    }
    return item;
  }
  function addForm() {
    const form = el("div", { className: "add" });
    const presetSelect = el("select", { name: "preset" });
    for (const preset of PRESETS) presetSelect.append(el("option", { value: preset.id, textContent: preset.label }));
    const model = el("input", { name: "model", placeholder: t.model, value: PRESETS[0].model });
    const url = el("input", { name: "url", placeholder: t.url, value: PRESETS[0].url ?? "" });
    const localInput = el("input", { type: "checkbox", name: "local", checked: true });
    const local = el("label", { className: "check" }, localInput, ` ${t.local}`);
    const sync = () => {
      const preset = PRESETS.find((item) => item.id === presetSelect.value);
      model.value = preset.model;
      url.value = preset.url ?? "";
      url.disabled = preset.url === null;
      local.hidden = preset.url === null;
      localInput.checked = !!preset.url && /^http:\/\/(127\.0\.0\.1|\[::1\]|localhost)/u.test(preset.url);
    };
    presetSelect.addEventListener("change", sync);
    const add = el("button", { type: "button", textContent: t.add, name: "add" });
    add.addEventListener("click", () => {
      const preset = PRESETS.find((item) => item.id === presetSelect.value);
      const taken = new Set(state.settings.backends.map((b) => b.id));
      let n = 1;
      while (taken.has(`${preset.id}-${n}`)) n++;
      const entry = { id: `${preset.id}-${n}`, preset: preset.id, enabled: true, model: model.value.trim() };
      if (preset.id === "emulated") entry.runtime = "ollama";
      if (preset.url !== null) entry.url = url.value.trim();
      if (preset.url !== null && localInput.checked) {
        try {
          const parsed = new URL(entry.url);
          entry.localConfirmed = { port: Number(parsed.port || (parsed.protocol === "https:" ? 443 : 80)), at: Date.now() };
        } catch {
        }
      }
      void save((s) => {
        s.backends.push(entry);
      });
    });
    form.append(presetSelect, model, url, add, local);
    return form;
  }
  function smartSection() {
    const smart = state.settings.smart;
    const model = el("input", { name: "smart-model", placeholder: t.smartModel, value: smart.kind === "ollama-chat" ? smart.model : "" });
    const saveSmart = el("button", { type: "button", textContent: t.add, name: "smart-save" });
    saveSmart.addEventListener("click", () => void save((s) => {
      s.smart = model.value.trim() ? { kind: "ollama-chat", url: "http://127.0.0.1:11434", model: model.value.trim() } : { kind: "none" };
    }));
    return el(
      "div",
      {},
      row(t.smart, el("span", {}, model, saveSmart)),
      checkbox(state.settings.shadowAsksSmart, t.smartAsk, (value) => void save((s) => {
        s.shadowAsksSmart = value;
      }), "shadow-asks-smart")
    );
  }
  function recentSection() {
    const list = el("ul", { className: "recent" });
    if (!state.recent.length) list.append(el("li", { className: "muted", textContent: t.noRecent }));
    for (const entry of state.recent.slice(0, 20)) {
      const item = el("li", {}, el("code", { textContent: entry.summary }), ` \u2192 ${entry.act ?? "\u2014"} (${entry.outcome}, ${entry.tier ?? "\u2014"}, ${entry.reason}) `);
      if (entry.auditId && entry.tier !== "rule" && !entry.label) {
        for (const verdict of ["right", "wrong"]) {
          const button = el("button", { type: "button", textContent: t[verdict] });
          button.addEventListener("click", async () => {
            await host.service.request(SERVICE, "feedback", { auditId: entry.auditId, verdict });
            await load();
          });
          item.append(button);
        }
      } else if (entry.label) item.append(el("span", { className: "muted", textContent: t[entry.label] }));
      list.append(item);
    }
    return list;
  }
  function render() {
    if (!state) return;
    const s = state.settings;
    const backends = el("ul", { className: "backends" });
    if (!s.backends.length) backends.append(el("li", { className: "muted", textContent: t.none }));
    for (const entry of s.backends) backends.append(backendRow(entry));
    root.replaceChildren(
      el("h1", { textContent: t.title }),
      el("p", { className: "muted", textContent: t.lead }),
      checkbox(s.enabled, t.enabled, (value) => void save((next) => {
        next.enabled = value;
      }), "enabled"),
      el("h2", { textContent: t.modes }),
      row(t.review, modeSelect("command.review")),
      row(t.triage, modeSelect("task.route")),
      el("p", { className: "muted", textContent: t.modeHelp }),
      row(t.strictness, select(s.reviewStrictness, [["triage", t.byTask], ["strict", t.always]], (value) => void save((next) => {
        next.reviewStrictness = value;
      }), "strictness")),
      checkbox(s.yoloOnlyIsolated, t.yolo, (value) => void save((next) => {
        next.yoloOnlyIsolated = value;
      }), "yolo"),
      el("h2", { textContent: t.backends }),
      backends,
      addForm(),
      smartSection(),
      el("h2", { textContent: t.data }),
      row(t.engine, select(s.engine, [["auto", t.engineAuto], ["jev", t.engineJev], ["local", t.engineLocal]], (value) => void save((next) => {
        next.engine = value;
      }), "engine")),
      row(t.dataMode, select(s.dataClassMode, [["strict", t.strict], ["warn", t.warn], ["off", t.dataOff]], (value) => void save((next) => {
        next.dataClassMode = value;
      }), "data-mode")),
      row(t.grant, select(s.grant, [["off", t.grantOff], ["D1", t.grantD1], ["D2", t.grantD2]], (value) => void save((next) => {
        next.grant = value;
      }), "grant")),
      row(t.defaultClass, select(s.defaultDataClass, [["D0", "D0"], ["D1", "D1"], ["D2", "D2"], ["D3", "D3"]], (value) => void save((next) => {
        next.defaultDataClass = value;
      }), "default-class")),
      el("h2", { textContent: t.recent }),
      recentSection()
    );
  }
  host.onContext(({ appearance }) => {
    t = appearance.locale === "ru" ? STRINGS.ru : STRINGS.en;
    document.documentElement.lang = appearance.locale;
    render();
  });
  host.service.onEvent(({ serviceId, event, data }) => {
    if (serviceId !== SERVICE || event !== "check") return;
    const result = data;
    say("error" in result ? result.error : result.added ? t.checkOk(result) : t.checkFail(result));
    void load();
  });
  load().catch((error) => say(errorText(error)));
})();
